site_name: Backend 2
site_url: https://jfinfocesde.github.io/25b2/
site_author: jhonfvg

theme:
  name: material
  language: es  
  icon:
    logo: octicons/code-16    
  features:    
    - navigation.tabs.sticky 
    - navigation.tabs
    - navigation.top
    # - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
  palette:    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode        

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false  

copyright: 2025 &copy; by JFVG

nav:
  - Inicio: index.md  
  - Contenido:
      - content/p1.md
      - content/p2.md
      - content/p3.md
      - content/p4.md
      - content/p5.md
      - content/p6.md
      - content/p7.md
      - content/p8.md
      - content/p9.md
      - content/p10.md
      - content/p11.md
      - content/p12.md
      # - content/p13.md
      # - content/p14.md
      # - content/p15.md
      # - content/p16.md
      # - content/p17.md
      # - content/p18.md 

  - Actividades:   
      - activities/p1.md
      - activities/p2.md
 
   

  - Tutoriales:   
      - tutorials/p1.md
      - tutorials/p2.md
      - tutorials/p3.md
      - Ejemplo Api Rest:   
          - api/00-estructura-proyecto.md
          - api/01-configuracion-inicial.md
          - api/02-configuracion-database.md
          - api/03-entidades-modelos.md
          - api/04-dtos-mapeo.md
          - api/05-repositorios-acceso-datos.md
          - api/06-servicios-logica-negocio.md
          - api/07-controladores-rest.md
          - api/08-actuator-monitoreo.md
          - api/09-validacion-manejo-errores.md
          - api/10-Repositorio.md

  - Proyecto Integrador:   
    - pi/p1.md
    - pi/p2.md

  # - Blog:
  #    - blog/index.md
  # - Acerca de: about.md

plugins:
  - search
  # - blog
  - glightbox

